from typing import Protocol


class AbstractStorage(Protocol):
    async def save(self, data: bytes, original_filename: str, checksum: str) -> str: ...
    async def delete(self, file_path: str) -> None: ...
    async def exists(self, file_path: str) -> bool: ...
